### ISSUE TITLE
Highlights/Notifications don't get pushed

### ISSUE THREAD

**Issue by rnyberg** [jamtur01/pushover-weechat#11]
I do not get push notificatiosns for highlights nor private messages. Using /pushover test works however. 

```
|plugins.var.perl.pushover.blacklist         string   ""
│plugins.var.perl.pushover.enabled           string   "on"
│plugins.var.perl.pushover.nma_apikey        string   ""
│plugins.var.perl.pushover.only_if_away      string   "off"
│plugins.var.perl.pushover.only_if_inactive  string   "off"
│plugins.var.perl.pushover.pb_apikey         string   "censored"
│plugins.var.perl.pushover.pb_device_iden    string   "censored"
│plugins.var.perl.pushover.priority          string   ""
│plugins.var.perl.pushover.rate_limit        string   "0"
│plugins.var.perl.pushover.redact_priv_msg   string   "off"
│plugins.var.perl.pushover.service           string   "pushbullet"
│plugins.var.perl.pushover.short_name        string   "off"
│plugins.var.perl.pushover.show_highlights   string   "on"
│plugins.var.perl.pushover.show_priv_msg     string   "on"
│plugins.var.perl.pushover.sound             string   ""
│plugins.var.perl.pushover.token             string   "censored"
│plugins.var.perl.pushover.user              string   "censored
|plugins.var.perl.pushover.verbose           string   "1"
```

**Comment by Berzerker** [comment]
You have your service set to pushbullet. Change it to pushover.

**Comment by rnyberg** [comment]
Will test it tomorrow.. Docs could be more clear since I set it to pb when trying to follow instructions.

**Comment by Berzerker** [comment]
Wouldn't that sound weird to you though? Even the documentation variables in the script tell you "this sets the service you want" and even offers pushover as an example.

**Comment by jamtur01** [comment]
Can you show me where it says to set it to that and I'll fix it up. Also any documentation pull requests welcomed!

**Comment by rnyberg** [comment]
I'll review my settings when I'm sober and will type here step by step how I interpret 'em so that the next Finnish drunk well get it right.

**Comment by Acnik** [comment]
Dont know if anyone reads this thread. but i have a similat problem.
The test command /pushover test sends test to my phone. But I dont get a notification when I'm mentioned. Im using pushbullet.

config:
`01:41:50 weechat     |   plugins.var.perl.pushover.blacklist = ""
01:41:50 weechat     |   plugins.var.perl.pushover.enabled = "on"
01:41:50 weechat     |   plugins.var.perl.pushover.nma_apikey = ""
01:41:50 weechat     |   plugins.var.perl.pushover.only_if_away = "off"
01:41:50 weechat     |   plugins.var.perl.pushover.only_if_inactive = "off"
01:41:50 weechat     |   plugins.var.perl.pushover.pb_apikey = "<pb-key>"
01:41:50 weechat     |   plugins.var.perl.pushover.pb_device_iden = ""
01:41:50 weechat     |   plugins.var.perl.pushover.priority = ""
01:41:50 weechat     |   plugins.var.perl.pushover.rate_limit = "0"
01:41:50 weechat     |   plugins.var.perl.pushover.redact_priv_msg = "off"
01:41:50 weechat     |   plugins.var.perl.pushover.service = "pushbullet"
01:41:50 weechat     |   plugins.var.perl.pushover.short_name = "off"
01:41:50 weechat     |   plugins.var.perl.pushover.show_highlights = "on"
01:41:50 weechat     |   plugins.var.perl.pushover.show_priv_msg = "on"
01:41:50 weechat     |   plugins.var.perl.pushover.sound = ""
01:41:50 weechat     |   plugins.var.perl.pushover.token = "<token>"
01:41:50 weechat     |   plugins.var.perl.pushover.user = ""
01:41:50 weechat     |   plugins.var.perl.pushover.verbose = "1"
`

**Comment by voidzero** [comment]
you guys are talking about the perl plugin, this is the ruby plugin.

**Comment by jamtur01** [comment]
Doh. Closing.
